### PR TITLE
Fixed incorrect variable usage in MongoDbResourceManager

### PR DESCRIPTION
**Pull request by careys7**
Updated incorrect `$this->resource` variable usages to `$this->resources` in MongoDbResourceManager.

### CODE REVIEW

**Comment by Ocramius** [comment]
Tests missing. Specifically: the fact that this didn't affect the build status means that we either:

 * simply don't test it
 * had unknown memory leaks
 * it's dead code, and not relevant at all

**Comment by careys7** [comment]
Updated with tests. 

Tests ensure that the instance of `MongoCollection` held for a given resource id does not persist following method calls to:
- `MongoDbResourceManager::setServer()`
- `MongoDbResourceManager::setCollection()`
- `MongoDbResourceManager::setConnectionOptions()`
- `MongoDbResourceManager::setDriverOptions()`
- `MongoDbResourceManager::setDatabase()`

**Comment by marc-mabe** [comment]
@careys7 Thanks for the fix! I have modified you test(s) to get batter coverage.

**Comment by careys7** [comment]
Your tests look better :+1:

**Pull request merged**
