### PR TITLE
Adding option to change cache and tag file suffixes

### PR DESCRIPTION
**Pull request by Lansoweb**
With this PR we can change the suffix for cache files. One use case is to use the filesystem cache to generate zend-view files (phtml suffixes).

### CODE REVIEW

**Comment by marc-mabe** [comment]
Thanks for contributing to zend-cache :)

I understand your use case and it's fine for me even if I think that's a very low used feature but I have one small problem with it:

What happens if the specified suffix contains a special character used by glob?
So you have to escape these characters! PHP doesn't have a function for that but I found one in [python](https://docs.python.org/3/library/glob.html#glob.escape)

Cheers

**Comment by weierophinney** [comment]
@Lansoweb I've rebased and incorporated the feedback from @marc-mabe .

**Comment by Lansoweb** [comment]
@weierophinney Great. Thanks!

**Comment by weierophinney** [comment]
Filesystem adapter unit tests run properly, so going to go ahead and merge to develop.

**Comment by weierophinney** [comment]
Thanks, @Lansoweb!

**Pull request merged**
