### PR TITLE
PHP 7.2 + QA Tools - follow up #129, #132, #134

### LINKED ISSUE #139: Add PHP 7.2 support, drop HHVM
- Update Travis configuration
- Check Travis results

### PR DESCRIPTION
**Pull request by webimpress**
Closes #129 
Closes #132 
Closes #134 
Resolves #139 

/cc @froschdesign

### CODE REVIEW

**Comment by marc-mabe** [comment]
Thanks for working on that but please split into smaller PRs

**Comment by webimpress** [comment]
I don't know how to configure all these cache adapters on travis for all supported PHP versions... I was trying multiple times and still something is failing 😞

**Comment by webimpress** [comment]
Sorry, closed by accident

**Comment by thomasvargiu** [comment]
@webimpress Can you try to split this PR? It's very complicated to review and test it.

**Comment by weierophinney** [comment]
@webimpress I tend to agree with @thomasvargiu , particularly as #132 is unrelated to QA tooling, and needs to be rewritten.

I'll merge #129 for now, and then start working on a patch that incorporates the QA-related commits from this one.

**Comment by weierophinney** [comment]
Closing in favor of #148, which incorporates commits from this patch.

**Pull request closed without merging**
