### PR TITLE
Fix undefined index persistent_id on RedisResourceManager

### PR DESCRIPTION
**Pull request by pensiero**
Probably a typo

### CODE REVIEW

**Comment by Ocramius** [comment]
Why isn't this caught by tests? Maybe missing coverage?

**Comment by pensiero** [comment]
Test cover only the possibility that is set a `persistent_id` or a `persistend_id` ([docs](https://github.com/zendframework/zend-cache/blob/master/test/Storage/Adapter/RedisResourceManagerTest.php#L119)) and that is found after been setted, but there are no test of the persistent_id about the `connect` method of `RedisResourceManager` ([connect](https://github.com/zendframework/zend-cache/blob/master/src/Storage/Adapter/RedisResourceManager.php#L261))

**Comment by pensiero** [comment]
Is it possible to merge this?

**Comment by marc-mabe** [comment]
@pensiero As you explained yourself this wasn't covered by a test -> please add a test case for it.

**Comment by pensiero** [comment]
I can try doing it in the next days, but meanwhile is it important to fix this typo that is very clear

**Comment by pensiero** [comment]
Moved to #9

**Pull request closed without merging**
