### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by remicollet**
Serializer is in the "require"

### CODE REVIEW

**Comment by gianarb** [comment]
:+1:

**Comment by marc-mabe** [comment]
I habe  a dejavu :)

The serializer is only needed for Thema serializer plugin and is not required for the hole component to work.
-> it should be in suggest only!

**Comment by weierophinney** [comment]
Agreed with @marc-mabe ; anything that is optional and not part of the default use case should be in "suggest" (as it currently is).

If you need that component for your _application_ use case, you should add it to your own dependencies, per the suggestion.

**Comment by remicollet** [comment]
@weierophinney if it is optional, please remove it from "require", current file is inconsistent.

**Comment by gianarb** [comment]
@weierophinney @marc-mabe maybe you have read bad this PR.. The problem is that `zendframework/zend-serializer` is suggested and required.. it's inconsistent IMO..

**Comment by marc-mabe** [comment]
@gianarb  zendframework/zf2#2960

**Comment by gianarb** [comment]
I don't understand.. Why zend-serializer is suggested and required!?

**Comment by marc-mabe** [comment]
@gianarb It should not be both that's indeed wrong. It should be 'suggest' only (and 'require-dev' for testing) as @remicollet did in #17

**Pull request closed without merging**
