### PR TITLE
Issue #185 : replacing deprecated delete() calls with del()

### PR DESCRIPTION
**Pull request by ppaulis**
Fixing Issue #185 
Since redis extension 5.0.0, Deprecation errors are thrown on every Redis::delete() call.
Replacing the delete() calls with del() calls fixes these messages.

### CODE REVIEW

**Comment by webimpress** [comment]
@ppaulis Please see PR I've created to your branch: http://github.com/ppaulis/zend-cache/pull/1
All tests there pass! :)

**Comment by tigrantv** [comment]
@ppaulis , @webimpress please prepare and push these changes to release

**Comment by pimjansen** [comment]
@webimpress i dont really think this is an enhancement but a bug which is blocking a lot nowadays?

**Comment by Ocramius** [comment]
Not a bug: needs to indeed land in a new minor, since we are *adding* compatibility with a new tool, not fixing a bug here.

**Comment by webimpress** [comment]
As @boesing checked del() is available since 2.1.0 release. Ref:
- https://github.com/phpredis/phpredis/tree/2.0.12#delete
- https://github.com/phpredis/phpredis/blob/2.1.0/README.markdown#del-delete

**Comment by webimpress** [comment]
Thanks, @ppaulis!

**Pull request merged**
