### PR TITLE
[travis-ci] Adjust tests available on Travis-CI platform

### PR DESCRIPTION
**Pull request by Maks3w**

### CODE REVIEW

**Comment by Maks3w** [comment]
Coverage increased (+17.18%) to 61.94%

**Comment by gianarb** [comment]
:+1:

**Comment by Maks3w** [comment]
Last commit remove version constraints in apc extension because is expected to be used with APCu instead APC (Deprecated since PHP 5.4)

**Comment by Maks3w** [comment]
Coverage increased (+23.15%) to 67.9%

**Comment by marc-mabe** [comment]
> Last commit remove version constraints in apc extension because is expected to be used with APCu instead APC (Deprecated since PHP 5.4)
What about replacing the APC adapter with a new one exactly for APCu that works well if APCu isn't in compatible mode

**Comment by Maks3w** [comment]
@marc-mabe Actual APC adapter is not failling with APCu

**Comment by marc-mabe** [comment]
@Maks3w I know as I did make it compatible ;) But if you compile APCu without full compatibility support there are no functions `apc_*` as all functions begin with `apcu_` -> see https://github.com/krakjoe/apcu/blob/db5d3db91470fdf07f6d873cba3f75326079869f/config.m4#L76

**Pull request merged**
